/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CacheStats */
        CacheStats: {
            /** Hits */
            hits: number;
            /** Misses */
            misses: number;
            /** Hit Rate */
            hit_rate: number;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "water" | "electricity" | "sanitation" | "roads" | "streetlights" | "other";
        /** ComplaintCreate */
        ComplaintCreate: {
            /**
             * Text
             * @description Free-text complaint
             */
            text: string;
            /** Location */
            location: string;
            /** Reporter Contact */
            reporter_contact?: string | null;
        };
        /** ComplaintOut */
        ComplaintOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text: string;
            /** Location */
            location: string;
            /** Reporter Contact */
            reporter_contact: string | null;
            category: components["schemas"]["Category"];
            priority: components["schemas"]["Priority"];
            status: components["schemas"]["Status"];
            /** Ai Summary */
            ai_summary: string | null;
            /** Triaged By */
            triaged_by: string;
            /** Triage Latency Ms */
            triage_latency_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Allowed Transitions
             * @description Statuses the backend will accept next. Computed by the state machine.
             */
            allowed_transitions?: components["schemas"]["Status"][];
        };
        /** ComplaintPage */
        ComplaintPage: {
            /** Items */
            items: components["schemas"]["ComplaintOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Detail */
            detail: string;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "high" | "normal" | "low";
        /** ProvidersOut */
        ProvidersOut: {
            /** Active Provider */
            active_provider: string;
            /** Fallback Provider */
            fallback_provider: string;
            /** Available Providers */
            available_providers: string[];
            triage_cache: components["schemas"]["CacheStats"];
            /** Recent */
            recent: components["schemas"]["TriageOutcome"][];
        };
        /** StatsOut */
        StatsOut: {
            /** Total */
            total: number;
            /** By Category */
            by_category: {
                [key: string]: number;
            };
            /** By Priority */
            by_priority: {
                [key: string]: number;
            };
            /** By Status */
            by_status: {
                [key: string]: number;
            };
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "open" | "in_progress" | "resolved" | "rejected";
        /** StatusUpdate */
        StatusUpdate: {
            status: components["schemas"]["Status"];
        };
        /** TriageOutcome */
        TriageOutcome: {
            /** Complaint Id */
            complaint_id: string;
            /** Provider */
            provider: string;
            /** Latency Ms */
            latency_ms: number;
            /** Fallback */
            fallback: boolean;
            /** Cache Hit */
            cache_hit: boolean;
            /** At */
            at: string;
        };
        /** ValidationErrorBody */
        ValidationErrorBody: {
            /** Detail */
            detail: string;
            /** Errors */
            errors: components["schemas"]["FieldError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
