# ruff: noqa: E501
"""Seed complaints: realistic, Urdu-influenced English, spread across every category.

Each tuple is (text, location, category, priority, status).
"""

SEED_COMPLAINTS: list[tuple[str, str, str, str, str]] = [
    # --- water -----------------------------------------------------------------------
    ("Burst water main flooding Street 12 since fajr, water entering ground floors of houses.",
     "Street 12, G-9/2, Islamabad", "water", "high", "open"),
    ("Paani nahi aa raha for 4 days in our mohalla, tanker mafia charging Rs 3000 per tanker.",
     "Block C, North Nazimabad, Karachi", "water", "high", "in_progress"),
    ("Pipeline leak near the masjid, clean water wasting on road since yesterday.",
     "Jamia Masjid Road, Samanabad, Lahore", "water", "normal", "open"),
    ("Water pressure very low on first floor, motor bhi kaam nahi karti. Please check the valve.",
     "Gulberg III, Lahore", "water", "normal", "open"),
    ("Dirty yellow water coming from tap, bachay beemar ho rahe hain. Urgent testing needed.",
     "Sector 11-A, Orangi Town, Karachi", "water", "high", "open"),
    ("Small drip from the water meter outside house no. 45, minor issue but please fix whenever.",
     "Street 7, F-10/3, Islamabad", "water", "low", "resolved"),
    # --- electricity -----------------------------------------------------------------
    ("Transformer sparking since last night near the school, bohat khatarnak hai, children pass daily.",
     "Model Town Link Road, Lahore", "electricity", "high", "open"),
    ("Load shedding 10 hours daily in our area even though schedule says 4 hours.",
     "Satellite Town, Rawalpindi", "electricity", "normal", "in_progress"),
    ("Bijli ki wires hanging very low over the street, trucks touching them.",
     "Main Bazaar, Sadiqabad, Rawalpindi", "electricity", "high", "open"),
    ("Voltage fluctuation damaged my fridge and fan, whole lane facing same problem.",
     "Street 3, Shah Faisal Colony, Karachi", "electricity", "normal", "open"),
    ("Electricity meter reading wrong, bill is triple of last month. Please send someone.",
     "Johar Town Block G, Lahore", "electricity", "low", "rejected"),
    ("Power outage since 2 am in whole sector, hospital nearby also on generator.",
     "Hayatabad Phase 3, Peshawar", "electricity", "high", "resolved"),
    # --- sanitation ------------------------------------------------------------------
    ("Gutter overflowing near masjid since two days, bachay school nahi ja sakte, bad smell everywhere.",
     "Mohalla Islampura, Gujranwala", "sanitation", "high", "open"),
    ("Kachra not collected for one week, dogs spreading garbage all over the street.",
     "Street 18, Gulshan-e-Iqbal Block 13, Karachi", "sanitation", "normal", "open"),
    ("Nala is blocked with plastic bags, rain water will flood houses if not cleaned before monsoon.",
     "Nullah Leh, Rawalpindi", "sanitation", "high", "in_progress"),
    ("Sewage water standing in the park, mosquito problem very bad, dengue ka khatra.",
     "Wapda Town Phase 1, Lahore", "sanitation", "high", "open"),
    ("Garbage dump next to vegetable market, smell comes inside the shops.",
     "Sabzi Mandi, Multan", "sanitation", "normal", "resolved"),
    ("Please place one more dustbin near the bus stop, small request from residents.",
     "Blue Area bus stop, Islamabad", "sanitation", "low", "open"),
    # --- roads -----------------------------------------------------------------------
    ("Huge pothole on the main road, two motorcycle accidents this week, someone will get injured.",
     "University Road, Peshawar", "roads", "high", "open"),
    ("Road construction left half done for 3 months, dust everywhere, sarak band hai.",
     "Canal Road near Thokar, Lahore", "roads", "normal", "in_progress"),
    ("Speed breaker without paint, cars jumping at night, please mark it.",
     "Street 22, DHA Phase 5, Karachi", "roads", "normal", "open"),
    ("Footpath tiles broken outside the girls college, elderly people falling.",
     "Jail Road, Lahore", "roads", "normal", "open"),
    ("Small crack in the service road, cosmetic issue, can be fixed in next repair round.",
     "I-8 Markaz service road, Islamabad", "roads", "low", "rejected"),
    ("Open manhole in the middle of the road, cover stolen, very dangerous at night.",
     "Saddar, Hyderabad", "roads", "high", "resolved"),
    # --- streetlights ----------------------------------------------------------------
    ("Street lights not working for 2 weeks, andhera hai, chori ki warda'at barh gayi hain.",
     "Street 5, Township Sector A1, Lahore", "streetlights", "high", "open"),
    ("Streetlight pole leaning dangerously after the storm, may fall on parked cars.",
     "Murree Road, Rawalpindi", "streetlights", "high", "in_progress"),
    ("Street light bulb fused near house 12, whole corner is dark after maghrib.",
     "Gulistan-e-Jauhar Block 7, Karachi", "streetlights", "normal", "open"),
    ("Street lights stay on during the day, wasting electricity, please fix the timer.",
     "F-7 Markaz, Islamabad", "streetlights", "low", "open"),
    ("Lamp in the park not working, families don't come in the evening anymore.",
     "Jinnah Park, Sialkot", "streetlights", "normal", "resolved"),
    # --- other -----------------------------------------------------------------------
    ("Stray dogs attacking people near the school gate, bachon ko dar lagta hai.",
     "Street 9, Faisal Town, Faisalabad", "other", "high", "open"),
    ("Illegal parking in front of my gate every evening, I cannot take my car out.",
     "Bahria Town Phase 4, Rawalpindi", "other", "normal", "open"),
    ("Loud wedding music till 3 am on weekdays, students cannot sleep before exams.",
     "Satellite Town Block B, Sargodha", "other", "low", "open"),
    ("Encroachment by shopkeepers on the footpath, people forced to walk on the road.",
     "Anarkali Bazaar, Lahore", "other", "normal", "in_progress"),
]
